include:
  - board: seeeduino_xiao_ble
    shield: chippy_left
  - board: seeeduino_xiao_ble
    shield: chippy_right
  - board: nice_nano_v2
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
